include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - 'example/**'

linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - prefer_single_quotes # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - unawaited_futures # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - unsafe_html # https://github.com/dart-lang/lints#migrating-from-packagepedantic
