include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - 'example/**'

linter:
  rules:
    - public_member_api_docs
