name: rxdart

packages:
  - examples/**
  - packages/**

scripts:
  analyze-no-private:
    run: melos exec --no-private -- dart analyze .
  analyze:
    run: melos exec -- dart analyze .
  format-no-private:
    run: melos exec --no-private -- dart format . --set-exit-if-changed
  format:
    run: melos exec -- dart format . --set-exit-if-changed
  pub-get-no-private:
    run: melos exec --no-private -- dart pub get
  test-rxdart:
    run: |
      cd \$MELOS_ROOT_PATH/packages/rxdart
      dart pub run test test/rxdart_test.dart --chain-stack-traces
      dart --disable-service-auth-codes --enable-vm-service=8111 --pause-isolates-on-exit --enable-asserts test/rxdart_test.dart &
      nohup dart pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates
      dart pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --report-on=lib
  generate:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.
  test-rxdart-flutter:
    run: |
      cd \$MELOS_ROOT_PATH/packages/rxdart_flutter
      flutter test --no-pub
