name: rxdart

packages:
  - examples/**
  - packages/**

scripts:
  analyze-no-private:
    run: melos exec --no-private -- dart analyze .
  analyze:
    run: melos exec -- dart analyze .
  test-rxdart:
    run: |
      cd \$MELOS_ROOT_PATH/packages/rxdart
      dart pub run test test/rxdart_test.dart --chain-stack-traces
  generate:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.