name: github_search
publish_to: 'none'
description: Flutter GitHub Search RxDart Example.

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart:
    path: ../../../packages/rxdart
  http: ^0.13.3
  flutter_spinkit: ^5.1.0
  rxdart_ext: ^0.3.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.17.10
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Bold.ttf
        - asset: fonts/montserrat/Montserrat-Regular.ttf
    - family: Hind
      fonts:
        - asset: fonts/hind/Hind-Regular.ttf
