include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - prefer_single_quotes # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - unawaited_futures # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - unsafe_html # https://github.com/dart-lang/lints#migrating-from-packagepedantic
