name: rxdart
version: 0.28.0
description: >
  RxDart is an implementation of the popular ReactiveX api for asynchronous
  programming, leveraging the native Dart Streams api.
repository: https://github.com/ReactiveX/rxdart

topics:
  - rxdart
  - reactive-programming
  - streams
  - observables
  - rx

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^1.0.1
  stack_trace: ^1.10.0
  test: ^1.17.12

screenshots:
  - description: The RxDart package logo.
    path: screenshots/logo.png
