name: rxdart_flutter
description: RxDart Flutter - Flutter Widgets that make it easy to use Streams with Flutter.
version: 0.0.1
repository: https://github.com/ReactiveX/rxdart/tree/master/packages/rxdart_flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.1'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

topics:
  - rxdart
  - reactive-programming
  - streams
  - observables
  - rx
